name: Simple CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: step1
        run: echo "this is my first pipeline"

      - name: step2
        run: echo "this is my second pipeline"   